### NumPy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. I will be focsing on the basics of NumPy, focusing on arrays and vectorized operations.


In [ ]:
!pip install numpy

In [1]:
import numpy as np

###create array using numpy
###create a 1D array 
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape([1,5])

array([[1, 2, 3, 4, 5]])

In [5]:
arr2 = np.array([[1,2,3,4,5]])
print(arr2)

[[1 2 3 4 5]]


In [6]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
##Overloading Operators for complex numbers
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [8]:
##Overloading Operators for complex numbers
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [9]:
#2d array 
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
##identical matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Array shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type:", arr.dtype)
print("Size of each element in bytes:", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Array shape: (2, 3)
Number of dimensions: 2
Data type: int32
Size of each element in bytes: 4


In [20]:
## Numpy array attributes

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10, 20, 30, 40, 50])

##Element-wise addition
print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)
print("Exponentiation:", arr1 ** 2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]
Exponentiation: [ 1  4  9 16 25]


In [21]:
## Universal functions
arr = np.array([2, 3, 4, 5, 6])
## Square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## Cosine
print(np.cos(arr))

## Tangent
print(np.tan(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
[-2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]


In [24]:
##Universal functions(ufuncs)

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n", arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
arr[0][0]

1

In [26]:
arr[2:]

array([[ 9, 10, 11, 12]])

In [27]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [29]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [30]:
##Modifying array
arr[0][0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [32]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [35]:
## statistical concepts - Normalisation
##to have a mean of 0 and standard deviation of 1

data = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Calculate mean and standard deviation
mean = np.mean(data)
print("Mean:", mean)

#median
median = np.median(data)
print("Median:", median)

#standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Normalization
normalized_data = (data - mean) / std_dev
print("Normalized Data:\n", normalized_data)

##vAriance
variance = np.var(data)
print("Variance:", variance)




Mean: 5.0
Median: 5.0
Standard Deviation: 2.581988897471611
Normalized Data:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
Variance: 6.666666666666667


In [37]:
## logical operations
data = np.array([1,2,3,4,5,6,7,8,9])

data[(data>= 5) & (data<=8)]

array([5, 6, 7, 8])